// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcUTXxe4ztRzI9y-OpVb9-NvvDfmI_n20',
    appId: '1:720657901610:web:7b05ecf249125f74c13b53',
    messagingSenderId: '720657901610',
    projectId: 'theserver-494f0',
    authDomain: 'theserver-494f0.firebaseapp.com',
    storageBucket: 'theserver-494f0.firebasestorage.app',
    measurementId: 'G-CM9SJLLRGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhRzWXtsrVjO8sQEbYfKQ2npNfGhjpDA',
    appId: '1:720657901610:android:aa369b4bdf79ea7fc13b53',
    messagingSenderId: '720657901610',
    projectId: 'theserver-494f0',
    storageBucket: 'theserver-494f0.firebasestorage.app',
    databaseURL: 'https://theserver-494f0-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmsdFLmKu0gwtr_l1wjHE_IQwgPbkB8M',
    appId: '1:720657901610:ios:d189621a569d8252c13b53',
    messagingSenderId: '720657901610',
    projectId: 'theserver-494f0',
    storageBucket: 'theserver-494f0.firebasestorage.app',
    iosBundleId: 'com.example.theServer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtmsdFLmKu0gwtr_l1wjHE_IQwgPbkB8M',
    appId: '1:720657901610:ios:d189621a569d8252c13b53',
    messagingSenderId: '720657901610',
    projectId: 'theserver-494f0',
    storageBucket: 'theserver-494f0.firebasestorage.app',
    iosBundleId: 'com.example.theServer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcUTXxe4ztRzI9y-OpVb9-NvvDfmI_n20',
    appId: '1:720657901610:web:fbc26819f220854ec13b53',
    messagingSenderId: '720657901610',
    projectId: 'theserver-494f0',
    authDomain: 'theserver-494f0.firebaseapp.com',
    storageBucket: 'theserver-494f0.firebasestorage.app',
    measurementId: 'G-RV50KWN9HL',
  );
}
